{application, erlando,
 [{description, "Syntax extensions for Erlang"},
  {vsn, "%%VSN%%"},
  {modules, [cut,
             do,
             error_t,
             identity_m,
             list_m,
             maybe_m,
             monad,
             monad_plus,
             omega_m,
             state_t,
             test
            ]},
  {registered, []},
  {applications, []}]}.
